### ISSUE TITLE
Restore minification as an option

### ISSUE THREAD

**Issue by mariusz-schimke** [vfrz/DotNetGraph#14]
One of the previous versions had the option to choose during compilation, whether to minify the diagram or not. It would be great if you allowed generating a non-minified diagram.

**Comment by vfrz** [comment]
Thank you for your suggestion. I have removed this option of the v2 because I didn't have the time to maintain this feature. However I understand your need, I will add this option as soon as I can.

**Comment by vfrz** [comment]
The option has been restored from V1 and is available as 2.1.0 on NuGet right now! 
Don't hesitate to report any bug or suggestion about it.

Thanks for your patience.
