### ISSUE TITLE
Missing Attribute Pos

### ISSUE THREAD

**Issue by lukascorona** [vfrz/DotNetGraph#19]
Currently the [pos attribute](https://graphviz.gitlab.io/_pages/doc/info/attrs.html#a:pos) is missing, which allows the position of a node to be specified. 
I want to add this attribute, but it is specified with a [point type](https://graphviz.gitlab.io/_pages/doc/info/attrs.html#k:point), which is simply a string in a specified format:

> "%f,%f('!')?" representing the point (x,y). The optional '!' indicates the node position should not change (input-only).

I'm not sure how and where to implement this point type and would therefore appreciate some advice.
In particular, I wonder if the point type should become its own class or is it sufficient if the DotPosAttribute contains the necessary conversion

**Comment by vfrz** [comment]
I've started a PR here to add position attribute to nodes and edges: #20
What do you think about it? Does it fill your need?

**Comment by vfrz** [comment]
The feature is now available on nuget as version 2.5.0
https://www.nuget.org/packages/DotNetGraph/2.5.0
