### ISSUE TITLE
Label question

### ISSUE THREAD

**Issue by LxLeChat** [vfrz/DotNetGraph#21]
Hello,
Thanks for the great work! very useful !
do you know how i can align to the left,  the label in a node
for example i have a multiline text in a label, and when it's displayed, everything is "centered" .. ! and i would like to align all text to the left !
thanks !

**Comment by vfrz** [comment]
Hello,
I believe this is not directly related to my library. You can have a look here to achieve what you want: http://www.graphviz.org/doc/info/attrs.html#k:escString
This part specifically:

> In addition, if the associated attribute is label, headlabel or taillabel, the escape sequences "\n", "\l" and "\r" divide the label into lines, centered, left-justified, and right-justified, respectively.

Hope this will help you, I am closing the issue for now.

**Comment by LxLeChat** [comment]
thanks for the answer and the links !

so i tried with something simple,  a single node with the following label : ``a\lb\lc\l``
and the compiled graph is as follow:
``graph "g" { "a"[label="\\la\\lb\\lc"]; }}`` 

so the escape sequence is .. escaped !
i think it's happening in the ``FormatString`` method of the ``DotCompiler`` Class

**Comment by vfrz** [comment]
Currently I don't really know how I could prevent the escaping since it does escape every backslash. Maybe I should just remove the `FormatString` method but then it makes breaking changes. I need to explore this further.

**Comment by LxLeChat** [comment]
Ok no problemo!
(i'm no c# export .. just a beginner ... ) but maybe we could create an attribute representing the "alignement" of the label ?
And add an override of the formatstring method ?

```
        internal static string FormatString(string value, string plop)
        {
            var result = value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r\n", "\\{plop}")
                .Replace("\n", "\\{plop}");

            return result;
        }
```

```
else if (attribute is DotLabelAttribute labelAttribute)
                {
                    attributeValues.Add($"label=\"{FormatString(labelAttribute.Text,labelAttribute.Alignement)}\"");
                }
```

**Comment by vfrz** [comment]
Thanks for your help but I am not sure your solution is ideal because it's seems we can't jump lines anymore. Another solution I've just thought about is to add a compiler option to disable string formatting, so you're free to do what you want but you need to escape everything yourself when needed. What do you think about that?

**Comment by LxLeChat** [comment]
Sure! For me this would do the trick.. i think :)

**Comment by vfrz** [comment]
I added the option in #22 
I will publish the NuGet soon. Sorry for the delay.

**Comment by LxLeChat** [comment]
Merci :)
