### ISSUE TITLE
How to specify `rankdir` graph attribute

### ISSUE THREAD

**Issue by YarekTyshchenko** [vfrz/DotNetGraph#33]
Nice project, exactly what I was looking for.

Very often I need a graph turned on its side to display text better.

```dot
graph g {
  graph[rankdir=LR];
  A -- B
}
```

**Comment by vfrz** [comment]
Hi, sorry for late response, I am slowly working on version 3.0 and I just added this feature: #32. I'll keep you updated when this new version will release!

**Comment by vfrz** [comment]
I have published a beta version available here: https://www.nuget.org/packages/DotNetGraph/3.0.0-beta2 with this new feature:
`var graph = new DotGraph().WithRankDir(DotRankDir.TB);`

**Comment by YarekTyshchenko** [comment]
sweet, thanks!
