### ISSUE TITLE
DotGraph.getNode(string identifier) or DotEdge.From(string identifier).To(string identifier)

### ISSUE THREAD

**Issue by FelixReuthlinger** [vfrz/DotNetGraph#39]
As suggestion to easier build bigger graphs without needing to always keep the previously created objects in the code block or pass them along I could think of either:
1. Adding a function to get a Node from an graph by passing the identifier of the node as string.
2. Letting everony create DotEdges from identifiers, since the DotNode and DotEdge anyways need to be added independently and in the end the important information would be the identifiers of the nodes you want to create an edge for.

**Comment by vfrz** [comment]
You already can create DotEdge with string identifiers using these extension methods:
https://github.com/vfrz/DotNetGraph/blob/498990eb23577cb742fc40aaefec90f4dd9e4fa1/Sources/DotNetGraph/Extensions/DotEdgeExtensions.cs#L8
https://github.com/vfrz/DotNetGraph/blob/498990eb23577cb742fc40aaefec90f4dd9e4fa1/Sources/DotNetGraph/Extensions/DotEdgeExtensions.cs#L20

Example:
`new DotEdge().From("node1").To("node2")`

But I like the idea to get a node (or an edge) by identifier from the graph object, so I might implement it!

**Comment by vfrz** [comment]
Added GetNodeByIdentifier to graph with 8b5d8c6
