### ISSUE TITLE
Feature Request: Add support for subgraphs/clusters

### ISSUE THREAD

**Issue by patroclos** [vfrz/DotNetGraph#4]
[reference](https://graphviz.gitlab.io/_pages/Gallery/directed/cluster.html)

**Comment by vfrz** [comment]
I'll work on this, I am currently rewriting most of the library. I hope to be able to release it before 2020.

**Comment by vfrz** [comment]
I have just published the new major version (2.0). It supports subgraph! 
There is some breaking changes, I invite you to take a look at the readme.
If you have any suggestion or encounter a bug feel free to open another issue.
